import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { ThemeSwitcher } from "@/components/ui/theme-switcher";
import { ThemeProvider } from "@/context/ThemeContext";
import CustomeSidebar from "@/components/ui/custome-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} flex min-h-screen ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <SidebarProvider defaultOpen={true}>
            <main className="flex min-h-screen">
              <CustomeSidebar />
              <SidebarTrigger className="opacity-60 hover:opacity-100" />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
